[default]
path ={origin ="./data", system_description = './data/systems/parameters.json'}
preprocessing_parameters={nperseg=1024}
simulation = {dt=0.0025,t_end = 10}
latent_coef = [1e-8,-200,-200,3575,-300,-3500,+1000,-450]